language: php
php:
  - 5.3

branches:
  only:
    - master

before_install:
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-source --no-interaction

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  irc: "irc.freenode.org#webforge-testdata"
  mail: p.scheit@ps-webforge.com